default: &default

development:
  <<: *default
  http_triggers:
    page: http://localhost:3000/
    content: http://localhost:3000/

test:
  <<: *default

production:
  <<: *default
  http_triggers:
    page: http://x-history-page.vdtapp.com/
    content: http://x-history-content.vdtapp.com/

